language: c
compiler: clang
script:
- chmod +x build.sh
- "./build.sh"
env:
  global:
  - secure: A421uRV5/K4wYH3mge9Ow3gKn045i8XMDlK7kdLk/HQ9geOtMoNxhlN9h+Oprd5xfAWKFRVQSKYOIf1GJm5PRQxIT+Qs93i8COY0EWmQ7YJpGImLnx/KKiPYCpXCx+ekMhLMbloaiAjU9Ua2YK/ShmgXWmdDA9Y33wjQxcrFRcEtNhSlWRmQ9dLtpiQvdY+o8IfusMuDx4k0PJ3gxmnBI3boaWFB1WByP4SHSaAopQAEu0hxU6e8HZ218pmteGa5fXIRyFCgHxOXl4aZ+Z8pw6K5qb5uZuKbTMtyO0pg+DFivfG+v+QBfJZ6wXE42CkeOemhTBjxTHGXRFxej3sIC7h+qvl+Dw3HhGRsHO8iqRlEWK6y6uEAMIphcDK0EPcJjWvWyFiU4ljXoJu+83SZP2KqHXb9k34H3VqzlqZRNFg3jyODjCN7IPRlt+4e6YxIAOGbplK8R0DKHyNeVSWv1mKhInRnWoWzEJ6DYJaFReXo9/gOMjajFHwLEVf1VsgbBBQj8O4C2xKKtUKWBCf9DitGBu+59+Z2iJGyu58IB1sgyl0/VmJDKimSRfQv4uhcpfX+miVWD+R327FVjgB+Vj5iuGllUsIXl/qtN6eh4sGmgiHpLA2W/eFDR3tB6rtsQb2Pbe/f0GJkHQPYr183rABvdq5CivUsqjMiZR5XxiE=
branches:
  only:
    - master
notifications:
  slack: emptystack:Xy9Q9tERJ6uosV0ubscxVIsG