language: c
compiler: clang
script:
- chmod +x build.sh
- "./build.sh"
env:
  global:
    secure: H73t/H78b4TgupoverftWl3dZ8GH0FRHjqs0MjcwooFvpkCjbLaCJRqvOjHVGY1xG9jjBc0AVzabcNHRMq4M3vCXfqV/SImTy87ABUgQ5GY65aMnBvJB5KdqKlklHPG4ZVaMiwlmYFU/KvA8v+V9+YxKtHjxHHCtpNqGt0QLiuHGOEBcX28CHyyMhnQ90eRcPt0RHeVsORxRLpyn8aAQJe3bGXqTaL5pqtRJW1aVoR5cuB2ZwwBYP8u+kOcXagZ7v7+zLoOGHYkrMpSt0ruuosZD5Jo3U5pniiJh2ppyRS+dUWxPDBa1PqT2iQlAl1Qjk8MJA4HWqTBqG0uVHpkY9TFKcO6Ki9TaDbI1a5+6x8lnIS0wqBlmHUiovIC1YO5jE7p1ISUfZFb4v0AHMkxdU5yQNYeB79N0P99Pt3nrfyTs+tpjIaW1QCJzNtz6Fo6Kz01y/jjiodhrY7hK+IjLCC1eCVwwT69X5c8X5qfU8b0sY9yxeEQyGVF/nySdbtl0WWbRi0hjsMb2T5rry3NiewmFkGAGHqepyaMN8eumpdr9zWH5YHMlhqiadXCdC4/sct17sKeclYBRZpHH4FkD+/pYXJzN8/Ron+PfjcHPeoFKMCfrzb+t1wxEn6TK8mdH9ff/gu4X/x6wqSv83gyUCqVqPs0QNSSxfMd8dv2LkJ4=
